src/DL/FamilytreeBundle/Entity/People.php
<?php

namespace DL\FamilytreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * People
 *
 * @ORM\Table(name="people")
 * @ORM\Entity(repositoryClass="DL\FamilytreeBundle\Repository\PeopleRepository")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class People
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255)
     */
    private $firstname;



    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=255)
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
    * NOTE: This is not a mapped field of entity metadata, just a simple property.
    *
    *@Assert\File(
    *   maxSize="2M",
    *   mimeTypes={"image/jpeg", "image/jpg", "image/png"},
    *   mimeTypesMessage = "Please upload a valid picture"
    *)
    * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
    *
    * @var File $image
    */
    private $imageFile;

    /**
    * @var \DateTime
    *
    * @ORM\Column(name="updateat", type="datetime", nullable=true)
    */
    private $updatedAt;

    /**
     *
     *
     * @ORM\ManyToOne(targetEntity="Tree", inversedBy="peoples", fetch="EAGER")
     * @ORM\JoinColumn(name="tree_id")
     *
     */
    private $tree;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return People
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return People
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return People
     */
    public function setImage($image)
    {
        $this->image = $image;

        if ($image instanceof UploadedFile) {
            $this->setUpdatedAt(new \DateTime());
        }

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }


    /**
    * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
    * of 'UploadedFile' is injected into this setter to trigger the  update. If this
    * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
    * must be able to accept an instance of 'File' as the bundle will inject one here
    * during Doctrine hydration.
    *
    * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
    *
    * @return People
    */
   public function setImageFile(File $image = null)
   {
       $this->imageFile = $image;

       if ($image) {
           // It is required that at least one field changes if you are using doctrine
           // otherwise the event listeners won't be called and the file is lost
           $this->updatedAt = new \DateTimeImmutable();
       }

       return $this;
   }

   /**
    * @return File|null
    */
   public function getImageFile()
   {
       return $this->imageFile;
   }

    /**
    * Permet d'afficher dans l'interface une concaténation du prénom et du nom
    */

   public function getLabel()
   {
       return $this->firstname . ' ' . $this->lastname;
   }




    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return People
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }


    /**
     * Set tree
     *
     * @param \DL\FamilytreeBundle\Entity\Tree $tree
     *
     * @return People
     */
    public function setTree(\DL\FamilytreeBundle\Entity\Tree $tree = null)
    {
        $this->tree = $tree;

        return $this;
    }

    /**
     * Get tree
     *
     * @return \DL\FamilytreeBundle\Entity\Tree
     */
    public function getTree()
    {
        return $this->tree;
    }
}

src/DL/FamilytreeBundle/Entity/Relation.php
<?php

namespace DL\FamilytreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Relation
 *
 * @ORM\Table(name="relation")
 * @ORM\Entity(repositoryClass="DL\FamilytreeBundle\Repository\RelationRepository")
 */
class Relation {

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
     *
     *
     * @ORM\ManyToOne(targetEntity="People", fetch="EAGER")
     * @ORM\JoinColumn(name="people_a_id", referencedColumnName="id")
     *
     */
    private $peopleA;


    /**
     *
     *
     * @ORM\ManyToOne(targetEntity="People", fetch="EAGER")
     * @ORM\JoinColumn(name="people_b_id", referencedColumnName="id")
     *
     */
    private $peopleB;


    /**
     *
     * @ORM\ManyToOne(targetEntity="Relationship", fetch="EAGER")
     * @ORM\JoinColumn(name="relationship_id", referencedColumnName="id")
     *
     */
    private $relationship;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Tree", fetch="EAGER")
     * @ORM\JoinColumn(name="tree_id", referencedColumnName="id")
     *
     */
    private $tree;





    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set peopleA
     *
     * @param \DL\FamilytreeBundle\Entity\People $peopleA
     *
     * @return Relation
     */
    public function setPeopleA(\DL\FamilytreeBundle\Entity\People $peopleA = null)
    {
        $this->peopleA = $peopleA;

        return $this;
    }

    /**
     * Get peopleA
     *
     * @return \DL\FamilytreeBundle\Entity\People
     */
    public function getPeopleA()
    {
        return $this->peopleA;
    }

    /**
     * Set peopleB
     *
     * @param \DL\FamilytreeBundle\Entity\People $peopleB
     *
     * @return Relation
     */
    public function setPeopleB(\DL\FamilytreeBundle\Entity\People $peopleB = null)
    {
        $this->peopleB = $peopleB;

        return $this;
    }

    /**
     * Get peopleB
     *
     * @return \DL\FamilytreeBundle\Entity\People
     */
    public function getPeopleB()
    {
        return $this->peopleB;
    }

    /**
     * Set relationship
     *
     * @param \DL\FamilytreeBundle\Entity\Relationship $relationship
     *
     * @return Relation
     */
    public function setRelationship(\DL\FamilytreeBundle\Entity\Relationship $relationship = null)
    {
        $this->relationship = $relationship;

        return $this;
    }

    /**
     * Get relationship
     *
     * @return \DL\FamilytreeBundle\Entity\Relationship
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    /**
     * Set tree
     *
     * @param \DL\FamilytreeBundle\Entity\Tree $tree
     *
     * @return Relation
     */
    public function setTree(\DL\FamilytreeBundle\Entity\Tree $tree = null)
    {
        $this->tree = $tree;

        return $this;
    }

    /**
     * Get tree
     *
     * @return \DL\FamilytreeBundle\Entity\Tree
     */
    public function getTree()
    {
        return $this->tree;
    }


    public function getPeoples()
    {
      $data = [];
      $data[] = $this->getPeopleA();
      $data[] = $this->getPeopleB();

    return $data;
    }


}

src/DL/FamilytreeBundle/Controller/RelationController.php
<?php

namespace DL\FamilytreeBundle\Controller;

use DL\FamilytreeBundle\Entity\Relation;
use DL\FamilytreeBundle\Form\Type\RelationFormType;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class RelationController extends Controller
{

    /**
    * @Route("/relation", name="relation")
    * @Security("has_role('ROLE_USER')")
    */
    public function indexAction(Request $request)
    {
        $relations = array();

        if($this->getUser()->getTree() != null)
        {
            // $relations = $this->getDoctrine()
            // ->getManager()
            // ->getRepository('DLFamilytreeBundle:Relation')
            // ->findByTree($this->getUser()->getTree()->getId());
            $relations = $this->container->get('security.token_storage')
              ->getToken()->getUser()->getTree()->getRelations();
        }


        $relation = new Relation();

        if( $this->getUser()->getTree() != null )    {

            $relation->setTree($this->getUser()->getTree());

        }

        $form = $this->createForm(RelationFormType::class, $relation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {

            if ($relation->getPeopleA()->getId()==$relation->getPeopleB()->getId()){

                $this->get('session')->getFlashBag()
                ->add('relationerror', 'Vous ne pouvez pas créer de relation sur une même personne.');

            }else if($this->checkRelationExistence($relation)){

                $this->get('session')->getFlashBag()
                ->add('relationerror', 'Cette relation existe déjà dans la base.');


            }else{
                $em = $this->getDoctrine()->getManager();
                $em->persist($relation);
                $em->flush();

                $this->get('session')->getFlashBag()
                ->add('relationok', "La relation " . $relation->getPeopleA()->getLabel() . " est " . $relation->getRelationship()->getName() . " de " . $relation->getPeopleB()->getLabel() . " a bien été créé.");


            }
            return $this->redirectToRoute('relation');
        }

        return $this->render('DLFamilytreeBundle:Relation:index.html.twig', [
            'form' => $form->createView(),
            'relations' => $relations,
        ]);
    }

    /**
    * Vérification du fait que la relation ne soit pas
    * déjà présente dans la base
    */
    public function checkRelationExistence($relation)
    {
        $relations = $this->getDoctrine()
        ->getManager()
        ->getRepository('DLFamilytreeBundle:Relation')
        ->findByTree($this->getUser()->getTree()->getId());

        foreach( $relations as $rel ){
            if ($rel->getPeopleA()->getId()==$relation->getPeopleA()->getId()
            && $rel->getPeopleB()->getId()==$relation->getPeopleB()->getId()
            && $rel->getRelationship()->getId()==$relation->getRelationship()->getId()){
                return true;
            }
        }
        return false;
    }

    /**
    * @Route("/relation/delete/{id}", name="relation_delete")
    * @Security("has_role('ROLE_USER')")
    */
    public function deleteAction(Request $request)
    {
        $id = $request->get('id');
        $em = $this->getDoctrine()->getManager();
        $relation = $em->getRepository('DLFamilytreeBundle:Relation')->find($id);
        if ($relation!=null) {      //Pour éviter le bug du double-clic (Merci Céline)
            $em->remove($relation);
            $em->flush();
        }

        return $this->redirectToRoute('relation');
    }

}

src/DL/FamilytreeBundle/Resources/views/Relation/createRelation.html.twig
{% extends 'base.html.twig' %}

src/DL/FamilytreeBundle/Resources/views/Relation/deleteRelation.html.twig
{% extends 'base.html.twig' %}

src/DL/FamilytreeBundle/Resources/views/Relation/index.html.twig
{% extends 'DLFamilytreeBundle::base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('bundles/DLFamilytreeBundle/css/vendor/purecss/pure-min.css') }}"/>
<link rel="stylesheet" href="{{ asset('bundles/DLFamilytreeBundle/css/relation/relation.css') }}" type="text/css" media="all"/>
{% endblock %}

{% block title %}Gestion des relations{% endblock %}


{% block message %}

<div class="message_error">

    {% if  app.session.flashbag.get('relationerror') is defined %}
    {% for flashMessage in app.session.flashbag.get('relationerror') %}

    <div class="alert alert-error" style="color : red">
        {{ flashMessage }}
    </div>

    {% endfor %}
    {% endif %}

</div>


<div class="message_ok">

    {% if  app.session.flashbag.get('relationok') is defined %}
    {% for flashMessage in app.session.flashbag.get('relationok') %}

    <div class="alert alert-success" style="color : green">
        {{ flashMessage }}
    </div>

    {% endfor %}
    {% endif %}

</div>
{% endblock %}
{% block body %}





    <div class="ajout-relation">
        <fieldset>
            <legend>
                Ajouter une relation
            </legend>
            {{ form_start(form, {"attr":{"class":"ajout-relation-form pure-form pure-form-aligned"}}) }}

            {{ form_widget(form.people_a) }}
            est
            {{ form_widget(form.relationship) }}
            de
            {{ form_widget(form.people_b) }}
            {{ form_widget(form.save) }}

            {{ form_end(form) }}
        </fieldset>
    </div>

    <div class="liste-relation">
        <fieldset>
            <legend>
                Liste des relations
            </legend>

            <table class="pure-table pure-table-striped">
                <thead>
                    <tr>
                        <th>Première Personne</th>
                        <th>Type</th>
                        <th>Deuxième Personne</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    {% for relation in relations %}
                    <tr>
                        <td>{{ relation.peopleA.label }}</td>
                        <td>{{ relation.relationship.name }}</td>
                        <td>{{ relation.peopleB.label }}</td>
                        <td><a href="{{ path("relation_delete", {'id':relation.id}) }}">Supprimer</a></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </fieldset>
    </div>


{% endblock %}

src/DL/FamilytreeBundle/Resources/views/Relation/listRelation.html.twig
{% extends 'base.html.twig' %}

src/DL/FamilytreeBundle/Resources/views/Relation/updateRelation.html.twig
{% extends 'base.html.twig' %}